# Generated by Django 3.1.3 on 2020-11-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WARD_DETAILS',
            fields=[
                ('Ward_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Capacity', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='DOCTOR_WORKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_details')),
                ('Ward_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ward.ward_details')),
            ],
            options={
                'unique_together': {('Ward_ID', 'Doc_ID')},
            },
        ),
    ]
