# Generated by Django 3.1.3 on 2020-11-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOCTOR_MONITOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TextField()),
                ('Status', models.BooleanField(default=True, verbose_name='Is the Doctor Healthy')),
                ('Drid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_details')),
            ],
            options={
                'unique_together': {('Drid', 'Time')},
            },
        ),
    ]
