# Generated by Django 3.1.3 on 2020-11-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_monitor',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
